%%{init: {'flowchart': {'nodeSpacing': 60, 'rankSpacing': 80, 'curve': 'linear'}} }%%
flowchart TB
    A[用户认证模块]
    A --> B[用户]
    B --> C[用户注册]
    B --> D[用户登录]
    B --> E[个人信息管理]
    B --> F[密码修改]
