%%{init: {'flowchart': {'nodeSpacing': 60, 'rankSpacing': 80, 'curve': 'linear'}} }%%
flowchart TB
    A[文档管理模块]
    A --> B[文档创建者/用户]
    B --> C[创建文档]
    B --> D[查看文档]
    B --> E[编辑文档]
    B --> F[发布与归档]
    B --> G[删除文档]
    B --> H[导出文档]
    B --> I[附件管理]
