%%{init: {'flowchart': {'nodeSpacing': 60, 'rankSpacing': 80, 'curve': 'linear'}} }%%
flowchart TB
    A[评论交流模块]
    A --> B[用户]
    B --> C[查看评论]
    B --> D[发表评论]
    B --> E[回复评论]
    B --> F[解决评论]
