%%{init: {'flowchart': {'nodeSpacing': 60, 'rankSpacing': 80, 'curve': 'linear'}} }%%
flowchart TB
    A[消息通知模块]
    A --> B[用户]
    B --> C[查看通知]
    B --> D[处理协作通知]
    B --> E[查看评论通知]
    B --> F[查看版本通知]
