%%{init: {'flowchart': {'nodeSpacing': 60, 'rankSpacing': 80, 'curve': 'linear'}} }%%
flowchart TB
    A[组织管理模块]
    A --> B[组织管理员]
    B --> C[组织成员管理]
    B --> D[部门管理]
    B --> E[组织文档管理]
    B --> F[组织版本审计]
    B --> G[组织统计分析]
