%%{init: {'flowchart': {'nodeSpacing': 60, 'rankSpacing': 80, 'curve': 'linear'}} }%%
flowchart TB
    A[平台管理模块]
    A --> B[系统管理员]
    B --> C[平台用户管理]
    B --> D[组织信息管理]
    B --> E[权限模板管理]
    B --> F[版本规则配置]
    B --> G[系统配置管理]
    B --> H[平台审计日志]
    B --> I[平台统计分析]
